title:            Go database/sql tutorial
description:      Use database/sql effectively!
safe: true
lsi: false
highlighter: rouge
timezone: UTC
markdown: kramdown

baseurl: https://hopher.github.io/go-database-sql-tutorial/
