version: '3'
services:
  jekyll:
      image: jekyll/jekyll:pages
      container_name: go-database-sql-tutorial
      command: jekyll serve --watch
      ports:
          - 3999:4000
      volumes:
          - ~/app/github.com/hopher/go-database-sql-tutorial:/srv/jekyll/